GET http://localhost:5000/api/v1/user/fdffd


###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjIiLCJpYXQiOjE2OTcwMTIyMzEsImV4cCI6MTY5NzQ0NDIzMX0.PlE9dkmjuIuN2uOeiXjDATkNpzOZ7JaAf52nFoYXD9g



###
GET  http://localhost:5000/api/v1/insert/
